site_name: 刘阳笔记屋
theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.top
  language: zh

plugins:
  - search:
      lang:
        - en
      separator: '[\s\-\.]+'
      prebuild_index: true


nav:
  - 首页: index.md
  - 前端: FE/前端笔记.md
  - Django: Python/Django.md
copyright: Copyright &copy; 2020 - 2021 刘阳

extra:
  generator: false
